import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { 
  Settings as SettingsIcon, 
  User, 
  Users, 
  Plus,
  Edit,
  Trash2,
  MapPin,
  Truck
} from "lucide-react";
import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/contexts/AuthContext";

const Settings = () => {
  const { toast } = useToast();
  const { userRole } = useAuth();
  const [customers, setCustomers] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [openCustomerDialog, setOpenCustomerDialog] = useState(false);
  const [editingCustomer, setEditingCustomer] = useState<any>(null);
  const [customerForm, setCustomerForm] = useState<{
    company_name: string;
    company_address: string;
    customer_type: "prepaid" | "credit";
    status: "active" | "frozen";
    credit_limit: number;
    payment_terms: number;
    payment_due_date: string;
    commission_type: string;
    commission_value: number;
  }>({
    company_name: "",
    company_address: "",
    customer_type: "prepaid",
    status: "active",
    credit_limit: 0,
    payment_terms: 0,
    payment_due_date: "",
    commission_type: "",
    commission_value: 0
  });

  useEffect(() => {
    if (userRole === "admin") {
      fetchCustomers();
    }
  }, [userRole]);

  const fetchCustomers = async () => {
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from("customers")
        .select("*")
        .order("created_at", { ascending: false });

      if (error) throw error;
      setCustomers(data || []);
    } catch (error: any) {
      toast({
        title: "错误",
        description: error.message,
        variant: "destructive"
      });
    } finally {
      setLoading(false);
    }
  };

  const handleSaveCustomer = async () => {
    try {
      if (editingCustomer) {
        // Update existing customer
        const { error } = await supabase
          .from("customers")
          .update(customerForm as any)
          .eq("id", editingCustomer.id);

        if (error) throw error;
        
        toast({
          title: "成功",
          description: "客户信息已更新"
        });
      } else {
        // Create new customer - customer_code will be auto-generated by trigger
        // We need to call the generate_customer_code function first
        const { data: codeData, error: codeError } = await supabase
          .rpc("generate_customer_code");

        if (codeError) throw codeError;

        const { error } = await supabase
          .from("customers")
          .insert([{
            ...customerForm,
            customer_code: codeData
          }]);

        if (error) throw error;
        
        toast({
          title: "成功",
          description: "客户已添加"
        });
      }

      setOpenCustomerDialog(false);
      resetForm();
      fetchCustomers();
    } catch (error: any) {
      toast({
        title: "错误",
        description: error.message,
        variant: "destructive"
      });
    }
  };

  const handleEditCustomer = (customer: any) => {
    setEditingCustomer(customer);
    setCustomerForm({
      company_name: customer.company_name,
      company_address: customer.company_address || "",
      customer_type: customer.customer_type,
      status: customer.status,
      credit_limit: customer.credit_limit || 0,
      payment_terms: customer.payment_terms || 0,
      payment_due_date: customer.payment_due_date || "",
      commission_type: customer.commission_type || "",
      commission_value: customer.commission_value || 0
    });
    setOpenCustomerDialog(true);
  };

  const handleDeleteCustomer = async (id: string) => {
    if (!confirm("确定要删除此客户吗？")) return;

    try {
      const { error } = await supabase
        .from("customers")
        .delete()
        .eq("id", id);

      if (error) throw error;

      toast({
        title: "成功",
        description: "客户已删除"
      });
      fetchCustomers();
    } catch (error: any) {
      toast({
        title: "错误",
        description: error.message,
        variant: "destructive"
      });
    }
  };

  const resetForm = () => {
    setEditingCustomer(null);
    setCustomerForm({
      company_name: "",
      company_address: "",
      customer_type: "prepaid",
      status: "active",
      credit_limit: 0,
      payment_terms: 0,
      payment_due_date: "",
      commission_type: "",
      commission_value: 0
    });
  };

  const consignees = [
    {
      id: "1",
      name: "ABC Electronics Inc.",
      address: "123 Tech Street, San Jose, CA 95110",
      contact: "John Smith",
      phone: "+1 (555) 123-4567"
    },
    {
      id: "2", 
      name: "XYZ Retail Corp.",
      address: "456 Commerce Ave, New York, NY 10001",
      contact: "Sarah Johnson",
      phone: "+1 (555) 987-6543"
    }
  ];

  const shippers = [
    {
      id: "1",
      name: "Global Manufacturing Ltd.",
      address: "789 Industrial Blvd, Detroit, MI 48201",
      contact: "Mike Wilson",
      phone: "+1 (555) 456-7890"
    }
  ];

  const subAccounts = [
    {
      id: "1",
      username: "operations_manager",
      name: "张经理",
      role: "订单管理员",
      status: "active",
      lastLogin: "2024-01-15"
    },
    {
      id: "2",
      username: "finance_clerk", 
      name: "李会计",
      role: "财务专员",
      status: "active",
      lastLogin: "2024-01-14"
    }
  ];

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">配置管理</h1>
        <p className="text-muted-foreground">管理收货人、发货人和子账号配置</p>
      </div>

      <Tabs defaultValue="users" className="w-full">
        <TabsList>
          <TabsTrigger value="users">用户配置</TabsTrigger>
          <TabsTrigger value="customers">客户配置</TabsTrigger>
          <TabsTrigger value="consignees">收货人配置</TabsTrigger>
          <TabsTrigger value="shippers">发货人配置</TabsTrigger>
        </TabsList>

        <TabsContent value="users">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <User className="h-5 w-5 text-primary" />
                  内部用户管理
                </span>
                <Button>
                  <Plus className="h-4 w-4 mr-2" />
                  添加用户
                </Button>
              </CardTitle>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>用户名</TableHead>
                    <TableHead>姓名</TableHead>
                    <TableHead>角色</TableHead>
                    <TableHead>权限</TableHead>
                    <TableHead>状态</TableHead>
                    <TableHead>最后登录</TableHead>
                    <TableHead>操作</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {subAccounts.map((account) => (
                    <TableRow key={account.id}>
                      <TableCell className="font-medium">{account.username}</TableCell>
                      <TableCell>{account.name}</TableCell>
                      <TableCell>{account.role}</TableCell>
                      <TableCell>
                        <Badge variant="outline">订单管理</Badge>
                      </TableCell>
                      <TableCell>
                        <Badge className="bg-success">活跃</Badge>
                      </TableCell>
                      <TableCell>{account.lastLogin}</TableCell>
                      <TableCell>
                        <div className="flex items-center gap-2">
                          <Button variant="outline" size="sm">
                            <Edit className="h-4 w-4" />
                          </Button>
                          <Button variant="outline" size="sm">
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="customers">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <Users className="h-5 w-5 text-primary" />
                  客户管理
                </span>
                <Dialog open={openCustomerDialog} onOpenChange={(open) => {
                  setOpenCustomerDialog(open);
                  if (!open) resetForm();
                }}>
                  <DialogTrigger asChild>
                    <Button>
                      <Plus className="h-4 w-4 mr-2" />
                      添加客户
                    </Button>
                  </DialogTrigger>
                  <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
                    <DialogHeader>
                      <DialogTitle>{editingCustomer ? "编辑客户" : "添加客户"}</DialogTitle>
                    </DialogHeader>
                    <div className="space-y-4 py-4">
                      <div className="grid grid-cols-2 gap-4">
                        <div className="space-y-2">
                          <Label htmlFor="company_name">公司名称 *</Label>
                          <Input
                            id="company_name"
                            value={customerForm.company_name}
                            onChange={(e) => setCustomerForm({ ...customerForm, company_name: e.target.value })}
                            placeholder="输入公司名称"
                          />
                        </div>
                        <div className="space-y-2">
                          <Label htmlFor="customer_type">客户类型 *</Label>
                          <Select
                            value={customerForm.customer_type}
                            onValueChange={(value) => setCustomerForm({ ...customerForm, customer_type: value as "prepaid" | "credit" })}
                          >
                            <SelectTrigger>
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem value="prepaid">预付</SelectItem>
                              <SelectItem value="credit">信用</SelectItem>
                            </SelectContent>
                          </Select>
                        </div>
                      </div>

                      <div className="space-y-2">
                        <Label htmlFor="company_address">公司地址</Label>
                        <Input
                          id="company_address"
                          value={customerForm.company_address}
                          onChange={(e) => setCustomerForm({ ...customerForm, company_address: e.target.value })}
                          placeholder="输入公司地址"
                        />
                      </div>

                      <div className="grid grid-cols-2 gap-4">
                        <div className="space-y-2">
                          <Label htmlFor="credit_limit">信用额度</Label>
                          <Input
                            id="credit_limit"
                            type="number"
                            value={customerForm.credit_limit}
                            onChange={(e) => setCustomerForm({ ...customerForm, credit_limit: parseFloat(e.target.value) || 0 })}
                            placeholder="0.00"
                          />
                        </div>
                        <div className="space-y-2">
                          <Label htmlFor="payment_terms">账期(天)</Label>
                          <Input
                            id="payment_terms"
                            type="number"
                            value={customerForm.payment_terms}
                            onChange={(e) => setCustomerForm({ ...customerForm, payment_terms: parseInt(e.target.value) || 0 })}
                            placeholder="0"
                          />
                        </div>
                      </div>

                      <div className="grid grid-cols-2 gap-4">
                        <div className="space-y-2">
                          <Label htmlFor="commission_type">佣金类型</Label>
                          <Select
                            value={customerForm.commission_type}
                            onValueChange={(value) => setCustomerForm({ ...customerForm, commission_type: value })}
                          >
                            <SelectTrigger>
                              <SelectValue placeholder="选择佣金类型" />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem value="percentage">百分比</SelectItem>
                              <SelectItem value="fixed">固定金额</SelectItem>
                            </SelectContent>
                          </Select>
                        </div>
                        <div className="space-y-2">
                          <Label htmlFor="commission_value">佣金值</Label>
                          <Input
                            id="commission_value"
                            type="number"
                            value={customerForm.commission_value}
                            onChange={(e) => setCustomerForm({ ...customerForm, commission_value: parseFloat(e.target.value) || 0 })}
                            placeholder="0.00"
                          />
                        </div>
                      </div>

                      <div className="space-y-2">
                        <Label htmlFor="status">状态</Label>
                        <Select
                          value={customerForm.status}
                          onValueChange={(value) => setCustomerForm({ ...customerForm, status: value as "active" | "frozen" })}
                        >
                          <SelectTrigger>
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="active">活跃</SelectItem>
                            <SelectItem value="frozen">冻结</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>

                      <div className="flex justify-end gap-2 pt-4">
                        <Button
                          variant="outline"
                          onClick={() => {
                            setOpenCustomerDialog(false);
                            resetForm();
                          }}
                        >
                          取消
                        </Button>
                        <Button onClick={handleSaveCustomer}>
                          {editingCustomer ? "更新" : "添加"}
                        </Button>
                      </div>
                    </div>
                  </DialogContent>
                </Dialog>
              </CardTitle>
            </CardHeader>
            <CardContent>
              {loading ? (
                <div className="text-center py-8">加载中...</div>
              ) : (
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>客户编码</TableHead>
                      <TableHead>公司名称</TableHead>
                      <TableHead>类型</TableHead>
                      <TableHead>信用额度</TableHead>
                      <TableHead>账期</TableHead>
                      <TableHead>佣金</TableHead>
                      <TableHead>余额</TableHead>
                      <TableHead>状态</TableHead>
                      <TableHead>操作</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {customers.length === 0 ? (
                      <TableRow>
                        <TableCell colSpan={9} className="text-center py-8 text-muted-foreground">
                          暂无客户数据
                        </TableCell>
                      </TableRow>
                    ) : (
                      customers.map((customer) => (
                        <TableRow key={customer.id}>
                          <TableCell className="font-medium">{customer.customer_code}</TableCell>
                          <TableCell>{customer.company_name}</TableCell>
                          <TableCell>
                            <Badge variant={customer.customer_type === "prepaid" ? "outline" : "secondary"}>
                              {customer.customer_type === "prepaid" ? "预付" : "信用"}
                            </Badge>
                          </TableCell>
                          <TableCell>${customer.credit_limit?.toLocaleString() || 0}</TableCell>
                          <TableCell>{customer.payment_terms || 0}天</TableCell>
                          <TableCell>
                            {customer.commission_type === "percentage" 
                              ? `${customer.commission_value}%` 
                              : `$${customer.commission_value}`}
                          </TableCell>
                          <TableCell>${customer.balance?.toLocaleString() || 0}</TableCell>
                          <TableCell>
                            <Badge className={customer.status === "active" ? "bg-success" : "bg-destructive"}>
                              {customer.status === "active" ? "活跃" : "冻结"}
                            </Badge>
                          </TableCell>
                          <TableCell>
                            <div className="flex items-center gap-2">
                              <Button 
                                variant="outline" 
                                size="sm"
                                onClick={() => handleEditCustomer(customer)}
                              >
                                <Edit className="h-4 w-4" />
                              </Button>
                              <Button 
                                variant="outline" 
                                size="sm"
                                onClick={() => handleDeleteCustomer(customer.id)}
                              >
                                <Trash2 className="h-4 w-4" />
                              </Button>
                            </div>
                          </TableCell>
                        </TableRow>
                      ))
                    )}
                  </TableBody>
                </Table>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="consignees">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <MapPin className="h-5 w-5 text-primary" />
                  收货人管理
                </span>
                <Button>
                  <Plus className="h-4 w-4 mr-2" />
                  添加收货人
                </Button>
              </CardTitle>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>公司名称</TableHead>
                    <TableHead>地址</TableHead>
                    <TableHead>联系人</TableHead>
                    <TableHead>电话</TableHead>
                    <TableHead>操作</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {consignees.map((consignee) => (
                    <TableRow key={consignee.id}>
                      <TableCell className="font-medium">{consignee.name}</TableCell>
                      <TableCell>{consignee.address}</TableCell>
                      <TableCell>{consignee.contact}</TableCell>
                      <TableCell>{consignee.phone}</TableCell>
                      <TableCell>
                        <div className="flex items-center gap-2">
                          <Button variant="outline" size="sm">
                            <Edit className="h-4 w-4" />
                          </Button>
                          <Button variant="outline" size="sm">
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="shippers">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <Truck className="h-5 w-5 text-primary" />
                  发货人管理
                </span>
                <Button>
                  <Plus className="h-4 w-4 mr-2" />
                  添加发货人
                </Button>
              </CardTitle>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>公司名称</TableHead>
                    <TableHead>地址</TableHead>
                    <TableHead>联系人</TableHead>
                    <TableHead>电话</TableHead>
                    <TableHead>操作</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {shippers.map((shipper) => (
                    <TableRow key={shipper.id}>
                      <TableCell className="font-medium">{shipper.name}</TableCell>
                      <TableCell>{shipper.address}</TableCell>
                      <TableCell>{shipper.contact}</TableCell>
                      <TableCell>{shipper.phone}</TableCell>
                      <TableCell>
                        <div className="flex items-center gap-2">
                          <Button variant="outline" size="sm">
                            <Edit className="h-4 w-4" />
                          </Button>
                          <Button variant="outline" size="sm">
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>

      </Tabs>
    </div>
  );
};

export default Settings;